## 1. Jupyter基本操作

In [10]:
# 命令模式

x = 1
print(x)

1


In [3]:
x = 10
x

10

In [7]:
x = 100
y = 10



10

In [14]:
for i in range(10):
    print(x)

1
1
1
1
1
1
1
1
1
1


## 2. 三个重要属性

## 3. 矩阵创建

In [ ]:
# 使用np.array()从Python列表创建NumPy数组
x = np.array([1,2,3])
x

In [ ]:
# 使用np.uint8()将数据转换为无符号8位整数类型（范围0-255），常用于图像像素值
y = np.uint8([1,1,1])

In [ ]:
# 查看数组的数据类型（dtype）
x.dtype

In [ ]:
# 使用np.float32()将数组转换为32位浮点数类型
np.float32(x)

In [ ]:
# np.arange()：生成等差序列，参数为(起始, 终止, 步长)，左闭右开
np.arange(2, 10, 1.5)

In [ ]:
# np.linspace()：在指定区间内生成均匀分布的点，参数为(起始, 终止, 点数)
np.linspace(0, 10, 11)

In [ ]:
# 生成从0到2π的100个均匀分布点，常用于三角函数绘图
np.linspace(0, 2*np.pi, 100)

In [ ]:
# np.zeros()：创建全零矩阵，dtype=np.uint8指定为无符号8位整数
np.zeros((2,4), dtype=np.uint8).dtype

In [ ]:
# np.ones()：创建全1矩阵，shape为(3,3)，dtype为float32
A = np.ones((3,3), dtype=np.float32)

In [ ]:
# np.eye(3)：创建3阶单位矩阵（对角线为1，其余为0）
np.eye(3)

In [ ]:
# np.identity(4)：创建4阶单位矩阵，与np.eye(4)效果相同
np.identity(4)

In [ ]:
# 创建10x10的随机整数矩阵，范围[0, 256)，模拟灰度图像像素值
np.random.randint(0, 256, (10,10), dtype=np.uint8)

## 4. 矩阵转换

In [74]:
import numpy as np

In [ ]:
# 创建3x3的全1矩阵，无符号8位整数类型
A = np.ones((3,3), dtype=np.uint8)

In [76]:
A

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=uint8)

In [ ]:
# reshape((-1,9))：将矩阵重塑为1行9列，-1表示自动计算该维度大小
A.reshape((-1,9)).shape

In [ ]:
# flatten()：将多维数组展平为一维数组（会创建副本）
A.flatten().shape

In [ ]:
# ravel()：将多维数组展平为一维数组（返回视图，不创建副本）
A.ravel()

In [83]:
A

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=uint8)

In [ ]:
# 创建3x3的随机整数矩阵，元素范围[0, 10)
B = np.random.randint(0, 10, (3,3))
B

In [ ]:
# B.T：矩阵转置，行变列，列变行
B.T

In [ ]:
# B.transpose()：矩阵转置，与B.T效果相同
B.transpose()

In [ ]:
# np.hstack()：水平方向拼接多个矩阵（按列拼接）
np.hstack([A, B, A, B])

## 5. 最大值、最小值、平均值

In [91]:
B

array([[0, 6, 3],
       [9, 2, 2],
       [9, 3, 3]])

In [ ]:
# B.max()：求矩阵所有元素中的最大值
B.max()

In [ ]:
# B.min()求最小值，B.mean()求平均值
B.min(), B.mean()

In [ ]:
# 使用np函数计算最大值、最小值、平均值，效果与方法调用相同
np.max(B), np.min(B), np.mean(B)

In [ ]:
# axis=1：沿行方向计算每行的最大值
B.max(axis=1)

In [ ]:
# 使用np.max()沿行方向计算每行的最大值
np.max(B, axis=1)

## 6. 数学运算

In [98]:
A

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=uint8)

In [99]:
B

array([[0, 6, 3],
       [9, 2, 2],
       [9, 3, 3]])

In [ ]:
# 矩阵逐元素加法
A + B

In [ ]:
# np.power(B, 2)：逐元素求平方
np.power(B, 2)

In [ ]:
# np.power(B, 0.5)：逐元素求0.5次方（开平方根）
np.power(B, 0.5)

In [ ]:
# np.sqrt(B)：逐元素开平方根，与np.power(B, 0.5)等价
np.sqrt(B)

In [ ]:
# np.log10(B+1)：逐元素取以10为底的对数，加1避免log(0)的情况
np.log10(B + 1)

In [108]:
A

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=uint8)

In [109]:
x

array([1, 2, 3])

In [ ]:
# A * x：逐元素相乘（广播机制），A的每行与x逐元素相乘
A * x

In [ ]:
# A @ x：矩阵乘法，A(3x3)与x(3,)做矩阵乘法
A @ x

In [ ]:
# A.dot(x)：矩阵乘法，与@运算符等价
A.dot(x)

In [ ]:
# A.dot(B)：矩阵乘法，A(3x3)与B(3x3)做矩阵乘法
A.dot(B)

## 7. 元素获取

In [114]:
B

array([[0, 6, 3],
       [9, 2, 2],
       [9, 3, 3]])

In [ ]:
# 获取第0行的所有元素
B[0, :]

In [ ]:
# 获取第1列的所有元素（:表示所有行）
B[:, 1]

In [ ]:
# 获取子矩阵：第1到2行、第1到2列的元素
B[1:3, 1:3]

In [ ]:
# 修改单个元素的值：将(0,0)位置设为10
B[0, 0] = 10

In [122]:
B

array([[10,  6,  3],
       [ 9,  2,  2],
       [ 9,  3,  3]])

In [ ]:
# 整行赋值：将第0行所有元素替换为[1,1,1]
B[0, :] = np.array([1,1,1])
B

## 7. 图片读写及显示

In [ ]:
# 导入所需的库
import numpy as np           # 数值计算库
import matplotlib.pyplot as plt  # 绑图库
import cv2 as cv              # OpenCV计算机视觉库

In [ ]:
# cv.imread()：读取图片，返回BGR格式的NumPy数组
img = cv.imread('pic/bear500x333.jpg')

In [ ]:
# cv.imwrite()：将图像保存到文件，参数为路径和图像数组
cv.imwrite('test/bear.jpg', img)

In [ ]:
# 使用OpenCV窗口显示图片
# cv.imshow()：创建窗口显示图片，参数为窗口名和图像数组
# cv.waitKey(0)：无限等待按键
# cv.destroyAllWindows()：关闭所有OpenCV窗口
cv.imshow('bear', img)
cv.waitKey(0)
cv.destroyAllWindows()

In [ ]:
# 使用matplotlib直接显示OpenCV读取的图片（颜色会不对，因为BGR顺序不匹配）
plt.imshow(img)
plt.show()

In [ ]:
# cv.cvtColor()：颜色空间转换，将BGR格式转为RGB格式以正确显示
img2 = cv.cvtColor(img, cv.COLOR_BGR2RGB)
plt.imshow(img2)
plt.show()

In [ ]:
# 以灰度模式读取图片（第二个参数0表示IMREAD_GRAYSCALE）
img3 = cv.imread('pic/bear500x333.jpg', 0)
# 使用OpenCV窗口显示灰度图片
cv.imshow('bear', img3)
cv.waitKey(0)
cv.destroyAllWindows()

In [ ]:
# 使用cmap='gray'正确显示灰度图像
plt.imshow(img3, cmap='gray')
plt.show()

In [ ]:
# 查看灰度图的维度：ndim=2表示二维（高度x宽度）
img3.ndim

In [ ]:
# 自定义显示函数：自动判断灰度图或彩色图并正确显示
def show(img):
    if img.ndim == 2:  # 灰度图
        plt.imshow(img, cmap='gray')
    else:  # 彩色图：需要BGR转RGB
        plt.imshow(cv.cvtColor(img, cv.COLOR_BGR2RGB))
    plt.show()

In [ ]:
# 使用自定义show函数显示彩色图片
apple = cv.imread('pic/apple.jpg')
show(apple)

In [ ]:
# 以灰度模式读取图片并显示
gray = cv.imread('pic/apple.jpg', 0)
show(gray)

## 9. 简单绘图

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# 生成绘图数据：x从2到19，y = 2x + 随机噪声
x = np.arange(2, 20)
y = 2 * x + np.random.randint(5, 20, 18)

In [ ]:
# plt.plot()绘制折线图，'+-'表示加号标记+实线，color='r'表示红色
plt.plot(x, y, '+-', color='r')
plt.show()

In [ ]:
# 生成0到1之间100个均匀分布点，计算三种幂函数曲线
x = np.linspace(0, 1, 100)
y1 = np.power(x, 0.5)  # y = x^0.5（开方曲线）
y2 = x                  # y = x（直线）
y3 = np.power(x, 1.5)  # y = x^1.5（幂函数曲线）

In [ ]:
# 同时显示三条曲线，添加图例、坐标标签、网格和坐标范围
plt.plot(x, y1, label='0.5')  # 指数0.5的曲线
plt.plot(x, y2, label='1.0')  # 指数1.0的直线
plt.plot(x, y3, label='1.5')  # 指数1.5的曲线
plt.legend()          # 显示图例
plt.xlabel('r')       # x轴标签
plt.ylabel('s')       # y轴标签
plt.grid()            # 显示网格
plt.xlim([0, 1])     # x轴范围
plt.ylim([0, 1])     # y轴范围
plt.show()

In [ ]:
# 生成1000个[0, 101)范围内的随机整数，用于绘制直方图
a = np.random.randint(0, 101, 1000)

In [ ]:
# 绘制直方图：rwidth=0.9设置柱宽比例，color='g'设置绿色
plt.hist(a, rwidth=0.9, color='g')
plt.show()

In [ ]:
# 生成自定义区间边界：从-0.5到101，步长为1
# 使用-0.5作为边界可以使整数值的柱子居中显示
bins = np.arange(-0.5, 101, 1)
bins

In [ ]:
# 使用自定义bins绘制更精细的直方图
plt.hist(a, bins)
plt.show()